feat: Added JSON check.
salsadigitalauorg/shipshape pull request #39
Opened 2023-11-01 07:34 UTC by sonnykt

2023-11-09 03:26 UTC, sonnykt commented
@steveworley docker build is failing with error:
```
#9 0.582 go: go.mod file indicates go 1.21, but maximum version supported by tidy is 1.20
#9 ERROR: process "/bin/sh -c GOOS=${TARGETOS} GOARCH=${TARGETARCH} &&     go mod tidy &&     go generate ./... &&     go build -ldflags=\"-s -w -X main.version=${VERSION} -X main.commit=${COMMIT}\" -o build/shipshape" did not complete successfully: exit code: 1
```

2023-11-09 03:32 UTC, steveworley requested changes

2023-11-09 03:32 UTC, steveworley commented on .github/workflows/go.yml
> +        go-version: 1.21
```suggestion
        go-version: 1.20
```
```
go: go.mod file indicates go 1.21, but maximum version supported by tidy is 1.20
```

2023-11-09 03:32 UTC, steveworley commented on .github/workflows/go.yml
> +        go-version: 1.21
```suggestion
        go-version: 1.20
```

2023-11-09 03:33 UTC, steveworley commented
Hey @sonnykt yeah `go mod tidy` doesn't look to support 1.21 just yet — so we'll have to pin to 1.20.

2023-11-09 03:40 UTC, yusufhm commented on go.mod
> +go 1.21
Another one here for pinning the go version:
```suggestion
go 1.20
```

2023-11-09 03:59 UTC, sonnykt commented
@steveworley turned out that we were using Docker image 1.20. I've increased the version to 1.21 and all good now.

2023-11-27 04:49 UTC, steveworley approved these changes

2023-11-27 04:49 UTC, merged